name: 'Repo Sync'
description: 'Keep forks and mirros up-to-date'
inputs:
  origin:
    description: 'Origin repository URL'
    required: true
  upstream:
    description: 'Upstream repository URL'
    required: true
  ssh-private-key:
    description: 'SSH private key'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    SSH_PRIVATE_KEY: ${{ inputs.ssh-private-key }}
  args:
    - ${{ inputs.origin }}
    - ${{ inputs.upstream }}
